---
abstract: 'Transform Math::Symbolic trees'
author:
  - 'Steffen Mueller <symbolic-module at steffen-mueller dot net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Symbolic-Custom-Transformation
provides:
  Math::Symbolic::Custom::Transformation:
    file: lib/Math/Symbolic/Custom/Transformation.pm
    version: 2.02
  Math::Symbolic::Custom::Transformation::Group:
    file: lib/Math/Symbolic/Custom/Transformation/Group.pm
    version: 2.02
requires:
  Math::Symbolic: 0.507
  Math::Symbolic::Custom::Pattern: 1.20
resources:
  license: http://dev.perl.org/licenses/
version: 2.02
